apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-app
  template:
    metadata:
      labels:
        app: multi-app
    spec:
      containers:
        - name: multi-app
          image: hagert/multi-app:${DOCKER_BRANCH_NAME}
          ports:
            - containerPort: 80