apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-app
  namespace: {{ NAMESPACE }}  # This will be replaced by the pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-app
  template:
    metadata:
      labels:
        app: multi-app
    spec:
      containers:
        - name: multi-app
          image: {{ DOCKER_IMAGE }}:{{ DOCKER_BRANCH_NAME }}  # This will be replaced by the pipeline
          ports:
            - containerPort: 80