apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-rolebinding
  namespace: main
subjects:
- kind: ServiceAccount
  name: jenkins-deployer
  namespace: main
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io